package education.artem.image_editor;

public enum OperationName {
    LINEAR_CONTRAST,
    EQUALIZE_CONTRAST,
    MEDIAN_FILTER,
    CONTOURS_PREWITT,
    CONTOURS_PREWITT_GRAYSCALE,
    CONTOURS_SOBEL,
    CONTOURS_SOBEL_GRAYSCALE,
    CONTOURS_LAPLASIAN_3X3,
    CONTOURS_LAPLASIAN_3X3_GRAYSCALE,
    CONTOURS_LAPLASIAN_5X5,
    CONTOURS_LAPLASIAN_5X5_GRAYSCALE,
    GAMMA_CORRECTION,
    BLUR,
    IDENTITY,
    GAUSSIAN_BLUR,
    EMBOSS,
    SHARPEN,
    BILATERAL
}
