package education.artem.contrastchangeandroid;

public enum OperationName {
    LINEAR_CONTRAST,
    EQUALIZE_CONTRAST,
    FILTER_3x3,
    FILTER_5x5,
    FILTER_7x7,
    FILTER_9x9,
    FILTER_11x11,
    CONTOURS_PREWITT,
    CONTOURS_PREWITT_GRAYSCALE,
    CONTOURS_SOBEL,
    CONTOURS_SOBEL_GRAYSCALE,
    CONTOURS_LAPLASIAN_3X3,
    CONTOURS_LAPLASIAN_3X3_GRAYSCALE,
    CONTOURS_LAPLASIAN_5X5,
    CONTOURS_LAPLASIAN_5X5_GRAYSCALE,
}
